name: Execute tests
on:
  workflow_call:
    inputs:
      basepath:
        required: false
        type: string
      os:
        required: true
        type: string
      workpath:
        required: true
        type: string

jobs:
  test:
    runs-on: ${{ inputs.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
    name: Python ${{ matrix.python-version }}

    defaults:
      run:
        working-directory: ${{ inputs.workpath }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Change path on Windows
        if: ${{ inputs.os == 'windows-latest' }}
        # Cannot start powershell from a path that does not exist, so change
        # working directory for this step only.
        working-directory: ${{ inputs.basepath }}
        run: |
          mkdir -p ${{ inputs.workpath }}
          mv $env:GITHUB_WORKSPACE\* ${{ inputs.workpath }}\ -Force
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - uses: Gr1N/setup-poetry@v7

      - uses: actions/cache@v2
        with:
          path: .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

      - name: Run tests
        run: poetry run pytest

      - name: Code check
        run: poetry run python tools/check_code.py
